import {
  Composer,
  ConnectionSummary,
  DiscoveryPanel,
  EmptyWorkspaceActions,
  FilePreviewPanel,
  MessageBubble,
  NavigationPanel,
  RawOutput,
  RemoteDirectoryDialog,
  RemoteDownloadDialog,
  SettingsPanel,
  TaskNotice,
  TopBar,
} from "../features/workbenchComponents.jsx";

export const shellComponents = {
  TopBar,
  NavigationPanel,
  ConnectionSummary,
  DiscoveryPanel,
  EmptyWorkspaceActions,
  MessageBubble,
  Composer,
  RawOutput,
  TaskNotice,
  SettingsPanel,
  FilePreviewPanel,
  RemoteDirectoryDialog,
  RemoteDownloadDialog,
};
